codecov:
  notify:
    require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  # post even if there are no changes in coverage
  require_changes: false
coverage:
  precision: 2
  range:
  - 95.0
  - 100.0
  round: down