// flow-typed signature: 1398d34ba31c04246952f77e315bce49
// flow-typed version: <<STUB>>/eslint-plugin-jest_v^21.15.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jest/processors/snapshot-processor' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/consistent-test-it' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/lowercase-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/no-disabled-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/no-focused-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/no-hooks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/no-identical-title' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/no-jest-import' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/no-large-snapshots' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/no-test-prefixes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/prefer-expect-assertions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/prefer-to-be-null' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/prefer-to-be-undefined' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/prefer-to-have-length' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/util' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/valid-describe' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/valid-expect-in-promise' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/valid-expect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jest/index' {
  declare module.exports: $Exports<'eslint-plugin-jest'>;
}
declare module 'eslint-plugin-jest/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jest'>;
}
declare module 'eslint-plugin-jest/processors/snapshot-processor.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/processors/snapshot-processor'>;
}
declare module 'eslint-plugin-jest/rules/consistent-test-it.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/consistent-test-it'>;
}
declare module 'eslint-plugin-jest/rules/lowercase-name.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/lowercase-name'>;
}
declare module 'eslint-plugin-jest/rules/no-disabled-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/no-disabled-tests'>;
}
declare module 'eslint-plugin-jest/rules/no-focused-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/no-focused-tests'>;
}
declare module 'eslint-plugin-jest/rules/no-hooks.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/no-hooks'>;
}
declare module 'eslint-plugin-jest/rules/no-identical-title.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/no-identical-title'>;
}
declare module 'eslint-plugin-jest/rules/no-jest-import.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/no-jest-import'>;
}
declare module 'eslint-plugin-jest/rules/no-large-snapshots.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/no-large-snapshots'>;
}
declare module 'eslint-plugin-jest/rules/no-test-prefixes.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/no-test-prefixes'>;
}
declare module 'eslint-plugin-jest/rules/prefer-expect-assertions.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/prefer-expect-assertions'>;
}
declare module 'eslint-plugin-jest/rules/prefer-to-be-null.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/prefer-to-be-null'>;
}
declare module 'eslint-plugin-jest/rules/prefer-to-be-undefined.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/prefer-to-be-undefined'>;
}
declare module 'eslint-plugin-jest/rules/prefer-to-have-length.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/prefer-to-have-length'>;
}
declare module 'eslint-plugin-jest/rules/util.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/util'>;
}
declare module 'eslint-plugin-jest/rules/valid-describe.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/valid-describe'>;
}
declare module 'eslint-plugin-jest/rules/valid-expect-in-promise.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/valid-expect-in-promise'>;
}
declare module 'eslint-plugin-jest/rules/valid-expect.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/valid-expect'>;
}
